### ISSUE TITLE
CSignalsViewer class was not found

### ISSUE THREAD

**Issue by zhao19851019** [MKlimenko/ugsdr#1]
I developed it on windows and compiled it with cmake,the CSignalsViewer class was not found

**Comment by MKlimenko** [comment]
Yes, that's an internal library for development and debugging purposes. I have no intention (or rights) to share it.
I was planning on making this dependency optional a little further down the road, currently, it only requires editing of the CMakeLists.txt in the [src](/mklimenko/ugsdr/blob/master/src/CMakeLists.txt) subfolder.

**Comment by MKlimenko** [comment]
@zhao19851019, fixed in my rtklib integration branch. I'll merge it into master when I'm done with GPS L2C and GLONASS L2OF observables.

**Comment by zhao19851019** [comment]
thank you!
